### ISSUE TITLE
Approval util functions

### ISSUE THREAD

**Issue by Oshioke-Salaki** [BlockheaderWeb3-Community/autoswappr-dapp#39] opened 2024-12-11 19:38 UTC
Create two functions in the utils file that does the following;

1. Calls the `approve` function of an erc20 contract. This function should take in the spenders address and amount.
2. Checks the amount of tokens that an owner approves a another to spend(allowance). This function should take in both the owner and spender addresses.

**ETA**
This issue is expected to be completed within 2 days of assignment. Failure to create a pull request (or draft pull request) within the expected time will lead to being unassigned.

**Comment by OWK50GA** [comment] 2024-12-11 19:42
Hi, @Oshioke-Salaki
I will like to take on this issue during the ODHack tomorrow.
I'm a Starknet Basecamp graduate, with special expertise in frontend integration, being originally a Frontend developer.

**Comment by Tzienom** [comment] 2024-12-12 06:09
Hi. Please I'd love to work on this issue.

**Comment by mimisavage** [comment] 2024-12-12 14:09
I'd like to handle this task.

**Comment by No-bodyq** [comment] 2024-12-12 14:14
Mind if I take this issue?

**Comment by aradix16** [comment] 2024-12-12 14:16
Hi!
I've already workend on Cairo contracts and would love to solve this issue to learn more about frontend interactions with Typescript. Thanks :)

**Comment by mimiprosper** [comment] 2024-12-12 14:18
I would like to take this task. Am a web 2 frontend developer, a technical writer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust.  If assigned this i would complete it within 2 days.

**Comment by anonfedora** [comment] 2024-12-12 14:41
Hi, I am Eleazar a fullstack blockchain developer, will use openzeppeling's implemntation of erc20 component to implement it's approve function as required, taking spenders address and amount.

**Comment by 0xdevcollins** [comment] 2024-12-12 14:55
I’d like to help with this.

**Comment by ryzen-xp** [comment] 2024-12-12 15:11
Hi, I am a proficient blockchain developer, expert in Cairo, Rust, Solidity, Aptos, and web development. I have contributed to projects like Chainevents and Arkprojects.

I can create the two utility functions for calling the approve function of an ERC-20 contract and checking the allowance between an owner and spender. Please assign this issue to me.

Thank you!

**Comment by Michaelkingsdev** [comment] 2024-12-12 15:14
Hello @LazarusAA 
I am a frontend developer with 4 years of experience. I would really love to work on this task. Can it be assigned to me?

**Comment by ShantelPeters** [comment] 2024-12-12 15:43
I'd love to work on this!

**Comment by Jagadeeshftw** [comment] 2024-12-12 18:16
Hello, I’d love to work on this issue as I have strong experience in developing secure and efficient smart contracts using Cairo and deploying them on StarkNet. Please assign this to me, and I’ll ensure to deliver a robust and high-quality PR within 12-24 hours.

**Comment by NueloSE** [comment] 2024-12-12 20:13
May I take care of this?

**Comment by Supa-mega** [comment] 2024-12-12 21:40
Can I try solving this issue? i have vast knowledge  in HTML , CSS , JAVASCRIPT ,TYP
ESCRIPT ETC ,,,,  will be glad to to contribute to this project and ecosystems  as a first time contributor

**Comment by emmz3230** [comment] 2024-12-12 21:55
Would love to tackle this!

I am a front-end developer specializing in responsive web design.
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute.
to open-source documentation and help build documentation sites.

**Comment by ikezuby2012** [comment] 2024-12-12 22:00
Hello, my name is nnubia nzube, I'm a full-stack developer with nearly 4 years of experience working with JavaScript, TypeScript, Reactjs, Nextjs, tailwindcss, Express.js, and recently exploring Cairo and rust for blockchain development. I’m passionate about building robust and scalable applications while ensuring clean and maintainable code.

i would like to work on this issue

**Comment by suhas-sensei** [comment] 2024-12-12 22:24
May I take this issue on? I'll create two utility functions for ERC20 token approvals and allowance checking with proper error handling. Having worked with ERC20 interactions, I'll implement clean interface calls for token approvals and balance checks before the 2 day mark.

**Comment by caxtonacollins** [comment] 2024-12-12 23:20
Would love to tackle this!

**Comment by DuendexCR** [comment] 2024-12-12 23:34
Could I try solving this?

**Comment by michojekunle** [comment] 2024-12-13 01:15
I'd love to give this a go.

**Comment by therealemino** [comment] 2024-12-13 01:32
Hi, I've over 4 years professional experience working on frontend applications (React, Vue, Next, Nuxt, TS). I've gone through the repository and I'd love to handle this. Can take on this task?

**Comment by davedumto** [comment] 2024-12-13 05:09
Hello, I'm David, a new open-source contributor, proficient in TypeScript, JavaScript, Tailwind CSS, and ShadCN. I can help create the two required utility functions by:

Implementing a function to call the approve method of an ERC-20 contract, accepting the spender’s address and amount.
Creating a function to check the allowance (approved token amount) between the owner and spender.
ETA 2 days

**Comment by ekumamatthew** [comment] 2024-12-13 08:14
Let me handle this issue!

**Comment by Luluameh** [comment] 2024-12-13 09:39
May I be assigned to this?

**Comment by Amarjeet325** [comment] 2024-12-13 09:52
Could I be assigned to this?

**Comment by casweeney** [comment] 2024-12-13 11:11
## Tackling this issue:

- I will create a function that follows the above listed specification, and I will ensure that the function works as intended.
- I will write test for the function.

**Closed** 2024-12-17 04:06 UTC
Labels: frontend, ODHack11
